---
- name: postfix reloaded (upstart)
  service: name=postfix state=reloaded
- name: postfix restarted (upstart)
  service: name=postfix state=restarted
- name: postfix started (upstart)
  service: name=postfix state=started
- name: postfix stoped (upstart)
  service: name=postfix state=stopd

- name: postfix reloaded (systemd)
  systemd: name=postfix state=reloaded
- name: postfix restarted (systemd)
  systemd: name=postfix state=restarted
- name: postfix started (systemd)
  systemd: name=postfix state=started
- name: postfix stoped (systemd)
  systemd: name=postfix state=stopd
